### ISSUE TITLE
bug: use of bash readline within contents causes EOF errors

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry-community/cron-boshrelease#13]
We utilize bash readline along with the cat command to write the contents of a configuration file. Something similar to:

```
cat <<EOF > $HOME/some/config
<config contents>
EOF
```

However, the script `/var/vcap/jobs/cron/bin/setup_crontab`, uses that same functionality. Because `contents` contains `EOF`, this causes the bash readline to have issues. Maybe there is another solution that can be used in this script? e.g. `echo -e "$contents" > some-file`, that reduces issues like this?

**Comment by lrstanley** [comment]
FWIW, I just changed our script to utilize the keyword `EOL` rather than `EOF`. Since the keyword isn't the same, it doesn't cause issues.

Bug is still relevant though. As, this was a silent error (doesn't show up in the `/var/vcap/sys/log/cron/` dir), so others will likely pull their hair out trying to figure out what's going on.

**Comment by jhunt** [comment]
Sadly the best bet is probably to replace EOL with a less frequently-used token, like `IAMTHECRONBOSHRELEASEANDTHISISMYEOF`

— Sent from a tiny screen and an even smaller keyboard.

**Comment by jhunt** [comment]
I've got a working local change that randomizes the EOF token by appending 32 randomly selected upper case latin alphabetic characters (A-Z) to the end.  I'll put in a PR.

**Comment by jhunt** [comment]
@lrstanley thoughts on https://github.com/cloudfoundry-community/cron-boshrelease/pull/14 ?

**Comment by lrstanley** [comment]
Sorry for the delay, haven't been in the office to test due to vacation. I'll be able to test in a week or two, though LGTM.
