### ISSUE TITLE
Please consider posting your bosh release on bosh.io

### ISSUE THREAD

**Issue by bsnchan** [cloudfoundry-community/cron-boshrelease#2]
Hello!

We found your cron bosh release and found it very useful for our bosh deployments. We were wondering if you would consider posting this release at [bosh.io](http://bosh.io/releases). We typically deploy our bosh deployments via CI pipelines and having this release on bosh.io would help us make our CI deployment easier.

Thanks,

Brenda and Derwei

**Comment by geofffranks** [comment]
Email sent, will close when I hear back

**Comment by jhunt** [comment]
@geofffranks you may want to ping @cppforlife again, he may have lost the email (maybe it was on an ephemeral disk?)

**Comment by cppforlife** [comment]
Added. Sorry, got lost in the pile.
