### ISSUE TITLE
Build new release

### ISSUE THREAD

**Issue by sharms** [cloudfoundry-community/cron-boshrelease#9]
There has been a patch merged since 2017, any chance a new release can be cut?

**Comment by jontours** [comment]
Can we please get the release cut?

**Comment by siennathesane** [comment]
//cc @geofffranks

**Comment by geofffranks** [comment]
//cc @jhunt

**Comment by jhunt** [comment]
v.1.2.0 is out! https://github.com/cloudfoundry-community/cron-boshrelease/releases/tag/v1.2.0

**Comment by siennathesane** [comment]
@jontours should be good now. :)
